
"use client";

import React, { createContext, useState, useContext, ReactNode, useCallback } from 'react';
import LanguageTransitionOverlay from '@/components/LanguageTransitionOverlay';

type Translations = { [key: string]: string };

const TRANSLATIONS_STORE: Record<string, Translations> = {
    'English': {
        nav_home: 'Home',
        nav_dashboard: 'Dashboard',
        nav_irrigation_planner: 'Irrigation Planner',
        nav_crop_advisor: 'Crop Advisor',
        nav_soil_advisor: 'Soil Advisor',
        nav_govt_schemes: 'Govt. Schemes',
        nav_about_us: 'About Us',
        nav_contact_us: 'Contact Us',
        hero_title: 'Revolutionizing Agriculture with AI',
        hero_subtitle: 'Samriddh Kheti provides data-driven insights to help Indian farmers optimize irrigation, improve crop yield, and increase profitability. Sustainable farming starts here.',
        hero_cta_primary: 'Go to Dashboard',
        hero_cta_secondary: 'Learn More',
        about_title: 'About Samriddh Kheti',
        about_subtitle: 'Empowering Indian farmers with data-driven insights for a sustainable future.',
        our_mission_title: 'Our Mission',
        our_mission_desc: 'To revolutionize agriculture in India by providing accessible, AI-powered tools that optimize resource usage, improve crop yields, and enhance the livelihoods of farmers.',
        our_vision_title: 'Our Vision',
        our_vision_desc: 'We envision a future where every farmer in India has the power of data and technology at their fingertips, leading to a prosperous, sustainable, and food-secure nation.',
        meet_team_title: 'Meet the Team',
        meet_team_subtitle: 'The passionate minds behind Samriddh Kheti.',
        'Jayesh Kumar Singh': 'Jayesh Kumar Singh',
        'Vidushi Srivastava': 'Vidushi Srivastava',
        'Kritika Singh': 'Kritika Singh',
        'jayeshkumarsingh11@gmail.com': 'jayeshkumarsingh11@gmail.com',
        'vidushi.official1012@gmail.com': 'vidushi.official1012@gmail.com',
        'kritikasince2005@gmail.com': 'kritikasince2005@gmail.com',
        contact_us_title: 'Contact Us',
        contact_us_subtitle: "We'd love to hear from you! Whether you have a question about our features, pricing, or anything else, our team is ready to answer all your questions.",
        contact_form_title: 'Send us a Message',
        contact_form_desc: "Fill out the form and we'll get back to you shortly.",
        form_name: 'Your Name',
        form_name_placeholder: 'Enter your full name',
        form_email: 'Your Email',
        form_email_placeholder: 'Enter your email address',
        form_subject: 'Subject',
        form_subject_placeholder: 'How can we help you?',
        form_message: 'Your Message',
        form_message_placeholder: 'Type your message here...',
        send_message_button: 'Send Message',
        next_irrigation: 'Next Irrigation',
        in_time_prefix: 'in',
        time_hour: 'hour',
        time_hours: 'hours',
        time_minute: 'minute',
        time_minutes: 'minutes',
        time_now: 'now',
        latest_schemes: 'Latest Schemes',
        scheme_pm_kisan_title: 'PM-KISAN',
        scheme_pm_kisan_desc: 'Income support for small farmers.',
        scheme_fasal_bima_title: 'Fasal Bima Yojana',
        scheme_fasal_bima_desc: 'Crop insurance against yield loss.',
        current_weather: 'Current Weather',
        current_location: 'Current Location',
        unknown_location: 'Unknown Location',
        could_not_fetch_location: 'Could not fetch location',
        weather_temperature: 'Temperature',
        weather_rain_chance: 'Rain Chance',
        weather_humidity: 'Humidity',
        weather_wind: 'Wind',
        weather_could_not_load: 'Could not load weather data.',
        forecast_title: '5-Day Forecast',
        forecast_not_available: 'Forecast not available.',
        latest_prices_title: 'Latest Prices',
        latest_prices_description: 'Govt. MSP vs. Local Vendor Price.',
        price_msp: 'MSP',
        price_local: 'Local',
        price_comparison_title: 'Crop Price Comparison',
        price_comparison_description: 'Govt. MSP vs. Local Vendor Price (₹ per Quintal).',
        price_search_crop_placeholder: 'Search Crop',
        price_msp_full: 'Govt. MSP',
        price_local_full: 'Local Vendor',
        price_analysis_title: 'Price Analysis',
        price_analysis_description: "AI-powered insights on the selected crop's price trends.",
        price_last_year_msp: 'Last Year MSP',
        price_current_msp: 'Current MSP',
        price_local_price: 'Local Price',
        price_analysis_select_crop_prompt: 'Select a crop to see price analysis.',
        get_price_analysis_button: 'Get Price Analysis',
        crop_advisor_title: 'Crop Advisor',
        crop_advisor_description: 'Get AI-powered crop recommendations tailored to your farm.',
        crop_advisor_initial_prompt: 'Discover the perfect crops for your land',
        crop_advisor_initial_prompt_desc: 'Fill in your farm details to get personalized, AI-driven suggestions.',
        form_location: 'Your Location',
        form_location_placeholder: 'e.g., Village, State',
        get_current_location_label: 'Get current location',
        form_farm_area: 'Farm Area (acres)',
        form_soil_type: 'Soil Type',
        form_soil_type_placeholder: 'Select soil',
        soil_loamy: 'Loamy',
        soil_clay: 'Clay',
        soil_sandy: 'Sandy',
        soil_alluvial: 'Alluvial',
        soil_black: 'Black Soil (Regur)',
        soil_red_yellow: 'Red and Yellow Soil',
        soil_laterite: 'Laterite Soil',
        form_water_availability: 'Water Availability',
        form_water_availability_placeholder: 'Select water availability',
        water_abundant: 'Abundant (Canal, River)',
        water_moderate: 'Moderate (Well, Borewell)',
        water_scarce: 'Scarce (Rain-fed)',
        form_primary_goal: 'Primary Goal',
        form_primary_goal_placeholder: 'What is your main goal?',
        goal_maximize_profit: 'Maximize Profit',
        goal_drought_resistant: 'Drought Resistant',
        goal_low_maintenance: 'Low Maintenance',
        goal_improve_soil: 'Improve Soil Health',
        form_crop_usage: 'Primary Crop Usage',
        form_crop_usage_placeholder: 'How will the crops be used?',
        usage_personal: 'Personal Use (Subsistence)',
        usage_local_market: 'Sell in Local Market',
        usage_commercial: 'Commercial Farming',
        get_recommendations_button: 'Get Recommendations',
        loading_analyzing_farm: 'Analyzing your farm...',
        loading_finding_crops: 'Our AI is finding the best crops for you.',
        results_top_recommendations: 'Top Crop Recommendations',
        results_why_suggested: 'Why we suggest this crop:',
        results_land_tip: 'Land Allocation Tip',
        results_profit_potential: 'Profit Potential',
        results_water_needs: 'Water Needs',
        results_growing_season: 'Growing Season',
        results_no_recommendations_title: 'No Specific Recommendations Found',
        results_no_recommendations_description: "We couldn't generate specific recommendations based on your inputs. Please try different criteria.",
        soil_advisor_title: 'Soil Quality Advisor',
        soil_advisor_description: "Get AI advice on improving your soil's health based on its history.",
        soil_advisor_initial_prompt: "Unlock your soil's potential",
        soil_advisor_initial_prompt_desc: "Provide your farm's history to receive tailored advice for better soil health.",
        form_past_crops: 'Past Crop History',
        form_past_crops_placeholder: 'Selected crops appear here',
        form_past_crops_search_placeholder: 'Search and add a crop...',
        form_past_crops_description: 'List crops from the last 2-3 seasons.',
        form_primary_goal_soil: 'Primary Goal for Soil',
        form_primary_goal_soil_placeholder: 'What is your main goal?',
        goal_increase_yield: 'Increase Yield',
        goal_reduce_fertilizer: 'Reduce Fertilizer Cost',
        goal_long_term_sustainability: 'Long-term Sustainability',
        goal_improve_water_retention: 'Improve Water Retention',
        get_soil_advice_button: 'Get Soil Advice',
        loading_analyzing_soil: "Analyzing your soil's history...",
        loading_preparing_soil_recommendations: 'Our AI soil scientist is preparing your recommendations.',
        results_soil_health_analysis: 'Initial Soil Health Analysis',
        results_improvement_recommendations: 'Improvement Recommendations',
        results_what_to_do: 'What to do:',
        results_how_to_implement: 'How to implement:',
        results_why_important: "Why it's important (Benefits):",
        error_unexpected: 'An unexpected error occurred.',
        irrigation_planner_title: 'Plan Your Irrigation',
        irrigation_planner_description: "Enter your farm's details to get a smart, dynamic irrigation schedule.",
        irrigation_planner_initial_prompt: 'Create your smart irrigation plan',
        irrigation_planner_initial_prompt_desc: 'Fill out the form to get a personalized, water-saving schedule.',
        form_crop_type: 'Crop Type',
        form_crop_type_placeholder: 'e.g., Wheat, Rice',
        form_water_source: 'Water Source',
        form_water_source_placeholder: 'Select a water source',
        water_source_canal: 'Canal',
        water_source_well: 'Well',
        water_source_borewell: 'Borewell',
        water_source_river: 'River',
        water_source_rainwater: 'Rainwater Harvesting',
        get_schedule_button: 'Get Schedule',
        loading_analyzing_farm_data: 'Analyzing your farm data...',
        loading_preparing_plan: 'Our AI is preparing your custom irrigation plan.',
        results_recommended_schedule: 'Recommended Schedule',
        results_schedule: 'Schedule',
        results_best_time: 'Best Time to Irrigate',
        results_precautions: 'Precautions',
        results_pesticides: 'Pesticide Recommendations',
        results_justification: 'Justification',
        error_fetching_location_weather: 'Could not fetch location or weather data. Please enter manually.',
        error_weather_data_not_available: 'Weather and soil data is not available yet. Please wait a moment and try again.',
        scheme_finder_title: 'Find Government Schemes',
        scheme_finder_description: 'Discover subsidies and schemes you are eligible for.',
        scheme_finder_initial_prompt: 'Find relevant government schemes',
        scheme_finder_initial_prompt_desc: 'Enter your details or click below to see popular national schemes.',
        form_primary_crop: 'Primary Crop',
        form_land_area: 'Land Area (acres)',
        find_schemes_button: 'Find Schemes',
        loading_finding_schemes: 'Finding relevant schemes...',
        loading_searching_programs: 'Our AI is searching for programs tailored to your needs.',
        results_suggested_schemes: 'Suggested Schemes for You',
        results_popular_schemes: 'Popular National Schemes',
        results_description: 'Description',
        results_eligibility: 'Eligibility',
        results_benefits: 'Benefits',
        results_how_to_apply: 'How to Apply',
        results_no_schemes_title: 'No Schemes Found',
        results_no_schemes_description: "We couldn't find any specific government schemes based on the information you provided. Please try adjusting your search criteria.",
        footer_quick_links: "Quick Links",
        footer_tools: "Tools",
        footer_newsletter: "Subscribe to our Newsletter",
        footer_newsletter_desc: "Get the latest updates on agricultural tech and government schemes.",
        footer_subscribe: "Subscribe",
        overall: 'Overall',
        wheat: 'Wheat',
        rice: 'Rice',
        maize: 'Maize',
        sugarcane: 'Sugarcane',
        cotton: 'Cotton',
        soybean: 'Soybean',
        groundnut: 'Groundnut',
        mustard: 'Mustard',
        potato: 'Potato',
        onion: 'Onion',
        tomato: 'Tomato',
        mango: 'Mango',
        banana: 'Banana',
        pulses: 'Pulses',
        jute: 'Jute',
        tea: 'Tea',
        coffee: 'Coffee',
        millet: 'Millet',
        barley: 'Barley',
        lentil: 'Lentil',
        gram: 'Gram',
        sorghum: 'Sorghum',
        bajra: 'Bajra',
        turmeric: 'Turmeric',
        ginger: 'Ginger',
        chilli: 'Chilli',
        capsicum: 'Capsicum',
        brinjal: 'Brinjal',
        okra: 'Okra',
        cabbage: 'Cabbage',
        cauliflower: 'Cauliflower',
        grapes: 'Grapes',
        apple: 'Apple',
        pomegranate: 'Pomegranate',
        guava: 'Guava',
        papaya: 'Papaya',
    },
    'Hindi': {
        nav_home: 'होम',
        nav_dashboard: 'डैशबोर्ड',
        nav_irrigation_planner: 'सिंचाई योजनाकार',
        nav_crop_advisor: 'फसल सलाहकार',
        nav_soil_advisor: 'मृदा सलाहकार',
        nav_govt_schemes: 'सरकारी योजनाएं',
        nav_about_us: 'हमारे बारे में',
        nav_contact_us: 'संपर्क करें',
        hero_title: 'एआई के साथ कृषि में क्रांति',
        hero_subtitle: 'समृद्ध खेती भारतीय किसानों को सिंचाई का अनुकूलन करने, फसल की उपज में सुधार करने और लाभप्रदता बढ़ाने में मदद करने के लिए डेटा-संचालित अंतर्दृष्टि प्रदान करती है। टिकाऊ खेती यहीं से शुरू होती है।',
        hero_cta_primary: 'डैशबोर्ड पर जाएं',
        hero_cta_secondary: 'और जानें',
        about_title: 'समृद्ध खेती के बारे में',
        about_subtitle: 'एक स्थायी भविष्य के लिए डेटा-संचालित अंतर्दृष्टि के साथ भारतीय किसानों को सशक्त बनाना।',
        our_mission_title: 'हमारा मिशन',
        our_mission_desc: 'भारत में कृषि में क्रांति लाना, सुलभ, एआई-संचालित उपकरण प्रदान करके जो संसाधन उपयोग को अनुकूलित करते हैं, फसल की पैदावार में सुधार करते हैं, और किसानों की आजीविका को बढ़ाते हैं।',
        our_vision_title: 'हमारा दृष्टिकोण',
        our_vision_desc: 'हम एक ऐसे भविष्य की कल्पना करते हैं जहां भारत में हर किसान के पास डेटा और प्रौद्योगिकी की शक्ति हो, जो एक समृद्ध, टिकाऊ और खाद्य-सुरक्षित राष्ट्र की ओर ले जाए।',
        meet_team_title: 'टीम से मिलें',
        meet_team_subtitle: 'समृद्ध खेती के पीछे के उत्साही दिमाग।',
        'Jayesh Kumar Singh': 'जयेश कुमार सिंह',
        'Vidushi Srivastava': 'विदुषी श्रीवास्तव',
        'Kritika Singh': 'कृतिका सिंह',
        'jayeshkumarsingh11@gmail.com': 'jayeshkumarsingh11@gmail.com',
        'vidushi.official1012@gmail.com': 'vidushi.official1012@gmail.com',
        'kritikasince2005@gmail.com': 'kritikasince2005@gmail.com',
        contact_us_title: 'संपर्क करें',
        contact_us_subtitle: 'हमें आपसे सुनना अच्छा लगेगा! चाहे आपके पास हमारी सुविधाओं, मूल्य निर्धारण, या किसी और चीज़ के बारे में कोई प्रश्न हो, हमारी टीम आपके सभी सवालों का जवाब देने के लिए तैयार है।',
        contact_form_title: 'हमें एक संदेश भेजें',
        contact_form_desc: 'फॉर्म भरें और हम जल्द ही आपसे संपर्क करेंगे।',
        form_name: 'आपका नाम',
        form_name_placeholder: 'अपना पूरा नाम दर्ज करें',
        form_email: 'आपका ईमेल',
        form_email_placeholder: 'अपना ईमेल पता दर्ज करें',
        form_subject: 'विषय',
        form_subject_placeholder: 'हम आपकी कैसे मदद कर सकते हैं?',
        form_message: 'आपका संदेश',
        form_message_placeholder: 'अपना संदेश यहां टाइप करें...',
        send_message_button: 'संदेश भेजें',
        next_irrigation: 'अगली सिंचाई',
        in_time_prefix: 'में',
        time_hour: 'घंटा',
        time_hours: 'घंटे',
        time_minute: 'मिनट',
        time_minutes: 'मिनट',
        time_now: 'अभी',
        latest_schemes: 'नवीनतम योजनाएं',
        scheme_pm_kisan_title: 'पीएम-किसान',
        scheme_pm_kisan_desc: 'छोटे किसानों के लिए आय सहायता।',
        scheme_fasal_bima_title: 'फसल बीमा योजना',
        scheme_fasal_bima_desc: 'उपज हानि के खिलाफ फसल बीमा।',
        current_weather: 'वर्तमान मौसम',
        current_location: 'वर्तमान स्थान',
        unknown_location: 'अज्ञात स्थान',
        could_not_fetch_location: 'स्थान प्राप्त नहीं कर सका',
        weather_temperature: 'तापमान',
        weather_rain_chance: 'बारिश की संभावना',
        weather_humidity: 'नमी',
        weather_wind: 'हवा',
        weather_could_not_load: 'मौसम डेटा लोड नहीं हो सका।',
        forecast_title: '5-दिवसीय पूर्वानुमान',
        forecast_not_available: 'पूर्वानुमान उपलब्ध नहीं है।',
        latest_prices_title: 'नवीनतम कीमतें',
        latest_prices_description: 'सरकारी एमएसपी बनाम स्थानीय विक्रेता मूल्य।',
        price_msp: 'एमएसपी',
        price_local: 'स्थानीय',
        price_comparison_title: 'फसल मूल्य तुलना',
        price_comparison_description: 'सरकारी एमएसपी बनाम स्थानीय विक्रेता मूल्य (₹ प्रति क्विंटल)।',
        price_search_crop_placeholder: 'फसल खोजें',
        price_msp_full: 'सरकारी एमएसपी',
        price_local_full: 'स्थानीय विक्रेता',
        price_analysis_title: 'मूल्य विश्लेषण',
        price_analysis_description: 'चयनित फसल के मूल्य रुझानों पर एआई-संचालित अंतर्दृष्टि।',
        price_last_year_msp: 'पिछले साल का एमएसपी',
        price_current_msp: 'वर्तमान एमएसपी',
        price_local_price: 'स्थानीय मूल्य',
        price_analysis_select_crop_prompt: 'मूल्य विश्लेषण देखने के लिए एक फसल का चयन करें।',
        get_price_analysis_button: 'मूल्य विश्लेषण प्राप्त करें',
        crop_advisor_title: 'फसल सलाहकार',
        crop_advisor_description: 'अपने खेत के लिए एआई-संचालित फसल सिफारिशें प्राप्त करें।',
        crop_advisor_initial_prompt: 'अपनी जमीन के लिए सही फसलें खोजें',
        crop_advisor_initial_prompt_desc: 'व्यक्तिगत, एआई-संचालित सुझाव प्राप्त करने के लिए अपने खेत का विवरण भरें।',
        form_location: 'आपका स्थान',
        form_location_placeholder: 'जैसे, गांव, राज्य',
        get_current_location_label: 'वर्तमान स्थान प्राप्त करें',
        form_farm_area: 'खेत का क्षेत्रफल (एकड़)',
        form_soil_type: 'मिट्टी का प्रकार',
        form_soil_type_placeholder: 'मिट्टी का चयन करें',
        soil_loamy: 'दोमट',
        soil_clay: 'चिकनी',
        soil_sandy: 'रेतीली',
        soil_alluvial: 'जलोढ़',
        soil_black: 'काली मिट्टी (रेगुर)',
        soil_red_yellow: 'लाल और पीली मिट्टी',
        soil_laterite: 'लेटराइट मिट्टी',
        form_water_availability: 'पानी की उपलब्धता',
        form_water_availability_placeholder: 'पानी की उपलब्धता का चयन करें',
        water_abundant: 'प्रचुर (नहर, नदी)',
        water_moderate: 'मध्यम (कुआँ, बोरवेल)',
        water_scarce: 'कम (वर्षा आधारित)',
        form_primary_goal: 'प्राथमिक लक्ष्य',
        form_primary_goal_placeholder: 'आपका मुख्य लक्ष्य क्या है?',
        goal_maximize_profit: 'अधिकतम लाभ',
        goal_drought_resistant: 'सूखा प्रतिरोधी',
        goal_low_maintenance: 'कम रखरखाव',
        goal_improve_soil: 'मिट्टी का स्वास्थ्य सुधारें',
        form_crop_usage: 'प्राथमिक फसल उपयोग',
        form_crop_usage_placeholder: 'फसलों का उपयोग कैसे किया जाएगा?',
        usage_personal: 'व्यक्तिगत उपयोग (निर्वाह)',
        usage_local_market: 'स्थानीय बाजार में बेचें',
        usage_commercial: 'वाणिज्यिक खेती',
        get_recommendations_button: 'सिफारिशें प्राप्त करें',
        loading_analyzing_farm: 'आपके खेत का विश्लेषण किया जा रहा है...',
        loading_finding_crops: 'हमारा एआई आपके लिए सबसे अच्छी फसलें ढूंढ रहा है।',
        results_top_recommendations: 'शीर्ष फसल सिफारिशें',
        results_why_suggested: 'हम इस फसल का सुझाव क्यों देते हैं:',
        results_land_tip: 'भूमि आवंटन युक्ति',
        results_profit_potential: 'लाभ की संभावना',
        results_water_needs: 'पानी की जरूरत',
        results_growing_season: 'बढ़ने का मौसम',
        results_no_recommendations_title: 'कोई विशेष सिफारिश नहीं मिली',
        results_no_recommendations_description: 'आपके इनपुट के आधार पर हम विशिष्ट सिफारिशें नहीं बना सके। कृपया विभिन्न मानदंडों का प्रयास करें।',
        soil_advisor_title: 'मृदा गुणवत्ता सलाहकार',
        soil_advisor_description: 'अपने मिट्टी के इतिहास के आधार पर उसके स्वास्थ्य को बेहतर बनाने के लिए एआई सलाह प्राप्त करें।',
        soil_advisor_initial_prompt: 'अपनी मिट्टी की क्षमता को अनलॉक करें',
        soil_advisor_initial_prompt_desc: 'बेहतर मिट्टी स्वास्थ्य के लिए अनुरूप सलाह प्राप्त करने के लिए अपने खेत का इतिहास प्रदान करें।',
        form_past_crops: 'पिछला फसल इतिहास',
        form_past_crops_placeholder: 'चयनित फसलें यहां दिखाई देती हैं',
        form_past_crops_search_placeholder: 'खोजें और एक फसल जोड़ें...',
        form_past_crops_description: 'पिछले 2-3 मौसमों की फसलें सूचीबद्ध करें।',
        form_primary_goal_soil: 'मिट्टी के लिए प्राथमिक लक्ष्य',
        form_primary_goal_soil_placeholder: 'आपका मुख्य लक्ष्य क्या है?',
        goal_increase_yield: 'उपज बढ़ाएँ',
        goal_reduce_fertilizer: 'उर्वरक लागत कम करें',
        goal_long_term_sustainability: 'दीर्घकालिक स्थिरता',
        goal_improve_water_retention: 'जल प्रतिधारण में सुधार करें',
        get_soil_advice_button: 'मिट्टी की सलाह लें',
        loading_analyzing_soil: 'आपकी मिट्टी के इतिहास का विश्लेषण किया जा रहा है...',
        loading_preparing_soil_recommendations: 'हमारे एआई मृदा वैज्ञानिक आपकी सिफारिशें तैयार कर रहे हैं।',
        results_soil_health_analysis: 'प्रारंभिक मृदा स्वास्थ्य विश्लेषण',
        results_improvement_recommendations: 'सुधार सिफारिशें',
        results_what_to_do: 'क्या करें:',
        results_how_to_implement: 'कैसे लागू करें:',
        results_why_important: 'यह क्यों महत्वपूर्ण है (लाभ):',
        error_unexpected: 'एक अप्रत्याशित त्रुटि हुई।',
        irrigation_planner_title: 'अपनी सिंचाई की योजना बनाएं',
        irrigation_planner_description: 'एक स्मार्ट, गतिशील सिंचाई कार्यक्रम प्राप्त करने के लिए अपने खेत का विवरण दर्ज करें।',
        irrigation_planner_initial_prompt: 'अपनी स्मार्ट सिंचाई योजना बनाएं',
        irrigation_planner_initial_prompt_desc: 'एक व्यक्तिगत, पानी बचाने वाला कार्यक्रम प्राप्त करने के लिए फॉर्म भरें।',
        form_crop_type: 'फसल का प्रकार',
        form_crop_type_placeholder: 'जैसे, गेहूं, चावल',
        form_water_source: 'जल स्रोत',
        form_water_source_placeholder: 'एक जल स्रोत का चयन करें',
        water_source_canal: 'नहर',
        water_source_well: 'कुआँ',
        water_source_borewell: 'बोरवेल',
        water_source_river: 'नदी',
        water_source_rainwater: 'वर्षा जल संचयन',
        get_schedule_button: 'कार्यक्रम प्राप्त करें',
        loading_analyzing_farm_data: 'आपके खेत के डेटा का विश्लेषण किया जा रहा है...',
        loading_preparing_plan: 'हमारा एआई आपकी कस्टम सिंचाई योजना तैयार कर रहा है।',
        results_recommended_schedule: 'अनुशंसित कार्यक्रम',
        results_schedule: 'कार्यक्रम',
        results_best_time: 'सिंचाई का सबसे अच्छा समय',
        results_precautions: 'सावधानियां',
        results_pesticides: 'कीटनाशक सिफारिशें',
        results_justification: 'औचित्य',
        error_fetching_location_weather: 'स्थान या मौसम डेटा प्राप्त नहीं कर सका। कृपया मैन्युअल रूप से दर्ज करें।',
        error_weather_data_not_available: 'मौसम और मिट्टी का डेटा अभी उपलब्ध नहीं है। कृपया थोड़ी देर प्रतीक्षा करें और पुनः प्रयास करें।',
        scheme_finder_title: 'सरकारी योजनाएं खोजें',
        scheme_finder_description: 'सब्सिडी और योजनाएं खोजें जिनके लिए आप पात्र हैं।',
        scheme_finder_initial_prompt: 'प्रासंगिक सरकारी योजनाएं खोजें',
        scheme_finder_initial_prompt_desc: 'लोकप्रिय राष्ट्रीय योजनाएं देखने के लिए अपना विवरण दर्ज करें या नीचे क्लिक करें।',
        form_primary_crop: 'प्राथमिक फसल',
        form_land_area: 'भूमि क्षेत्र (एकड़)',
        find_schemes_button: 'योजनाएं खोजें',
        loading_finding_schemes: 'प्रासंगिक योजनाएं ढूंढी जा रही हैं...',
        loading_searching_programs: 'हमारा एआई आपकी आवश्यकताओं के अनुरूप कार्यक्रम खोज रहा है।',
        results_suggested_schemes: 'आपके लिए सुझाई गई योजनाएं',
        results_popular_schemes: 'लोकप्रिय राष्ट्रीय योजनाएं',
        results_description: 'विवरण',
        results_eligibility: 'पात्रता',
        results_benefits: 'लाभ',
        results_how_to_apply: 'आवेदन कैसे करें',
        results_no_schemes_title: 'कोई योजना नहीं मिली',
        results_no_schemes_description: 'आपके द्वारा दी गई जानकारी के आधार पर हमें कोई विशिष्ट सरकारी योजना नहीं मिली। कृपया अपनी खोज मानदंडों को समायोजित करने का प्रयास करें।',
        footer_quick_links: 'त्वरित लिंक्स',
        footer_tools: 'उपकरण',
        footer_newsletter: 'हमारे न्यूज़लेटर की सदस्यता लें',
        footer_newsletter_desc: 'कृषि तकनीक और सरकारी योजनाओं पर नवीनतम अपडेट प्राप्त करें।',
        footer_subscribe: 'सदस्यता लें',
        overall: 'कुल मिलाकर',
        wheat: 'गेहूँ',
        rice: 'चावल',
        maize: 'मक्का',
        sugarcane: 'गन्ना',
        cotton: 'कपास',
        soybean: 'सोयाबीन',
        groundnut: 'मूंगफली',
        mustard: 'सरसों',
        potato: 'आलू',
        onion: 'प्याज',
        tomato: 'टमाटर',
        mango: 'आम',
        banana: 'केला',
        pulses: 'दालें',
        jute: 'जूट',
        tea: 'चाय',
        coffee: 'कॉफी',
        millet: 'बाजरा',
        barley: 'जौ',
        lentil: 'मसूर',
        gram: 'चना',
        sorghum: 'ज्वार',
        bajra: 'बाजरा',
        turmeric: 'हल्दी',
        ginger: 'अदरक',
        chilli: 'मिर्च',
        capsicum: 'शिमला मिर्च',
        brinjal: 'बैंगन',
        okra: 'भिंडी',
        cabbage: 'पत्ता गोभी',
        cauliflower: 'फूलगोभी',
        grapes: 'अंगूर',
        apple: 'सेब',
        pomegranate: 'अनार',
        guava: 'अमरूद',
        papaya: 'पपीता',
    },
    'Marathi': {
        nav_home: 'होम',
        nav_dashboard: 'डॅशबोर्ड',
        nav_irrigation_planner: 'सिंचन नियोजक',
        nav_crop_advisor: 'पीक सल्लागार',
        nav_soil_advisor: 'मृदा सल्लागार',
        nav_govt_schemes: 'सरकारी योजना',
        nav_about_us: 'आमच्याबद्दल',
        nav_contact_us: 'संपर्क साधा',
        hero_title: 'एआयसह कृषी क्षेत्रात क्रांती',
        hero_subtitle: 'समृद्ध खेती भारतीय शेतकऱ्यांना सिंचन ऑप्टिमाइझ करण्यासाठी, पिकांचे उत्पादन सुधारण्यासाठी आणि नफा वाढवण्यासाठी डेटा-आधारित अंतर्दृष्टी प्रदान करते. शाश्वत शेती येथून सुरू होते.',
        hero_cta_primary: 'डॅशबोर्डवर जा',
        hero_cta_secondary: 'अधिक जाणून घ्या',
        about_title: 'समृद्ध खेती बद्दल',
        about_subtitle: 'शाश्वत भविष्यासाठी डेटा-आधारित अंतर्दृष्टीसह भारतीय शेतकऱ्यांना सक्षम करणे.',
        our_mission_title: 'आमचे ध्येय',
        our_mission_desc: 'भारतातील कृषी क्षेत्रात क्रांती घडवणे, सुलभ, एआय-शक्तीवर चालणारी साधने प्रदान करून जे संसाधनांचा वापर ऑप्टिमाइझ करतात, पिकांचे उत्पादन सुधारतात आणि शेतकऱ्यांचे जीवनमान उंचावतात.',
        our_vision_title: 'आमची दृष्टी',
        our_vision_desc: 'आम्ही अशा भविष्याची कल्पना करतो जिथे भारतातील प्रत्येक शेतकऱ्याच्या बोटांच्या टोकावर डेटा आणि तंत्रज्ञानाची शक्ती असेल, ज्यामुळे एक समृद्ध, शाश्वत आणि अन्न-सुरक्षित राष्ट्र बनेल.',
        meet_team_title: 'टीमशी भेटा',
        meet_team_subtitle: 'समृद्ध खेतीमागील उत्साही मने.',
        'Jayesh Kumar Singh': 'जयेश कुमार सिंग',
        'Vidushi Srivastava': 'विदुषी श्रीवास्तव',
        'Kritika Singh': 'कृतिका सिंग',
        'jayeshkumarsingh11@gmail.com': 'jayeshkumarsingh11@gmail.com',
        'vidushi.official1012@gmail.com': 'vidushi.official1012@gmail.com',
        'kritikasince2005@gmail.com': 'kritikasince2005@gmail.com',
        contact_us_title: 'संपर्क साधा',
        contact_us_subtitle: 'आम्हाला तुमच्याकडून ऐकायला आवडेल! आमच्या वैशिष्ट्ये, किंमत किंवा इतर कोणत्याही गोष्टीबद्दल तुमचा प्रश्न असो, आमची टीम तुमच्या सर्व प्रश्नांची उत्तरे देण्यासाठी तयार आहे.',
        contact_form_title: 'आम्हाला संदेश पाठवा',
        contact_form_desc: 'फॉर्म भरा आणि आम्ही लवकरच तुमच्याशी संपर्क साधू.',
        form_name: 'तुमचे नाव',
        form_name_placeholder: 'तुमचे पूर्ण नाव प्रविष्ट करा',
        form_email: 'तुमचा ईमेल',
        form_email_placeholder: 'तुमचा ईमेल पत्ता प्रविष्ट करा',
        form_subject: 'विषय',
        form_subject_placeholder: 'आम्ही तुमची कशी मदत करू शकतो?',
        form_message: 'तुमचा संदेश',
        form_message_placeholder: 'तुमचा संदेश येथे टाइप करा...',
        send_message_button: 'संदेश पाठवा',
        next_irrigation: 'पुढील सिंचन',
        in_time_prefix: 'मध्ये',
        time_hour: 'तास',
        time_hours: 'तास',
        time_minute: 'मिनिट',
        time_minutes: 'मिनिटे',
        time_now: 'आता',
        latest_schemes: 'नवीनतम योजना',
        scheme_pm_kisan_title: 'पीएम-किसान',
        scheme_pm_kisan_desc: 'छोट्या शेतकऱ्यांसाठी उत्पन्न समर्थन.',
        scheme_fasal_bima_title: 'फसल विमा योजना',
        scheme_fasal_bima_desc: 'उत्पादन नुकसानीविरूद्ध पीक विमा.',
        current_weather: 'सध्याचे हवामान',
        current_location: 'सध्याचे स्थान',
        unknown_location: 'अज्ञात स्थान',
        could_not_fetch_location: 'स्थान मिळू शकले नाही',
        weather_temperature: 'तापमान',
        weather_rain_chance: 'पावसाची शक्यता',
        weather_humidity: 'आर्द्रता',
        weather_wind: 'वारा',
        weather_could_not_load: 'हवामान डेटा लोड होऊ शकला नाही.',
        forecast_title: '5-दिवसांचा अंदाज',
        forecast_not_available: 'अंदाज उपलब्ध नाही.',
        latest_prices_title: 'नवीनतम किमती',
        latest_prices_description: 'सरकारी एमएसपी वि. स्थानिक विक्रेता किंमत.',
        price_msp: 'एमएसपी',
        price_local: 'स्थानिक',
        price_comparison_title: 'पीक किंमत तुलना',
        price_comparison_description: 'सरकारी एमएसपी वि. स्थानिक विक्रेता किंमत (₹ प्रति क्विंटल).',
        price_search_crop_placeholder: 'पीक शोधा',
        price_msp_full: 'सरकारी एमएसपी',
        price_local_full: 'स्थानिक विक्रेता',
        price_analysis_title: 'किंमत विश्लेषण',
        price_analysis_description: 'निवडलेल्या पिकाच्या किंमतीच्या ट्रेंडवर एआय-शक्तीवर चालणारी अंतर्दृष्टी.',
        price_last_year_msp: 'मागील वर्षीची एमएसपी',
        price_current_msp: 'सध्याची एमएसपी',
        price_local_price: 'स्थानिक किंमत',
        price_analysis_select_crop_prompt: 'किंमत विश्लेषण पाहण्यासाठी पीक निवडा.',
        get_price_analysis_button: 'किंमत विश्लेषण मिळवा',
        crop_advisor_title: 'पीक सल्लागार',
        crop_advisor_description: 'तुमच्या शेतासाठी एआय-शक्तीवर चालणाऱ्या पीक शिफारसी मिळवा.',
        crop_advisor_initial_prompt: 'तुमच्या जमिनीसाठी परिपूर्ण पिके शोधा',
        crop_advisor_initial_prompt_desc: 'वैयक्तिकृत, एआय-चालित सूचना मिळवण्यासाठी तुमच्या शेताचा तपशील भरा.',
        form_location: 'तुमचे स्थान',
        form_location_placeholder: 'उदा. गाव, राज्य',
        get_current_location_label: 'सध्याचे स्थान मिळवा',
        form_farm_area: 'शेताचे क्षेत्र (एकर)',
        form_soil_type: 'मातीचा प्रकार',
        form_soil_type_placeholder: 'माती निवडा',
        soil_loamy: 'लोमी',
        soil_clay: 'चिकणमाती',
        soil_sandy: 'वाळूमय',
        soil_alluvial: 'गाळाची',
        soil_black: 'काळी माती (रेगुर)',
        soil_red_yellow: 'लाल आणि पिवळी माती',
        soil_laterite: 'लॅटराइट माती',
        form_water_availability: 'पाण्याची उपलब्धता',
        form_water_availability_placeholder: 'पाण्याची उपलब्धता निवडा',
        water_abundant: 'भरपूर (कालवा, नदी)',
        water_moderate: 'मध्यम (विहीर, बोअरवेल)',
        water_scarce: 'अपुरी (पावसावर अवलंबून)',
        form_primary_goal: 'प्राथमिक ध्येय',
        form_primary_goal_placeholder: 'तुमचे मुख्य ध्येय काय आहे?',
        goal_maximize_profit: 'नफा वाढवा',
        goal_drought_resistant: 'दुष्काळ प्रतिरोधक',
        goal_low_maintenance: 'कमी देखभाल',
        goal_improve_soil: 'मातीचे आरोग्य सुधारा',
        form_crop_usage: 'प्राथमिक पीक वापर',
        form_crop_usage_placeholder: 'पिकांचा वापर कसा केला जाईल?',
        usage_personal: 'वैयक्तिक वापर (निर्वाह)',
        usage_local_market: 'स्थानिक बाजारात विक्री',
        usage_commercial: 'व्यावसायिक शेती',
        get_recommendations_button: 'शिफारसी मिळवा',
        loading_analyzing_farm: 'तुमच्या शेताचे विश्लेषण करत आहे...',
        loading_finding_crops: 'आमचे एआय तुमच्यासाठी सर्वोत्तम पिके शोधत आहे.',
        results_top_recommendations: 'शीर्ष पीक शिफारसी',
        results_why_suggested: 'आम्ही या पिकाची सूचना का देतो:',
        results_land_tip: 'जमीन वाटप टीप',
        results_profit_potential: 'नफ्याची शक्यता',
        results_water_needs: 'पाण्याची गरज',
        results_growing_season: 'वाढीचा हंगाम',
        results_no_recommendations_title: 'कोणतीही विशिष्ट शिफारस आढळली नाही',
        results_no_recommendations_description: 'तुमच्या इनपुटवर आधारित आम्ही विशिष्ट शिफारसी तयार करू शकलो नाही. कृपया भिन्न निकष वापरून पहा.',
        soil_advisor_title: 'मृदा गुणवत्ता सल्लागार',
        soil_advisor_description: 'तुमच्या मातीच्या इतिहासावर आधारित तिचे आरोग्य सुधारण्यासाठी एआय सल्ला मिळवा.',
        soil_advisor_initial_prompt: 'तुमच्या मातीची क्षमता अनलॉक करा',
        soil_advisor_initial_prompt_desc: 'उत्तम माती आरोग्यासाठी अनुरूप सल्ला मिळवण्यासाठी तुमच्या शेताचा इतिहास प्रदान करा.',
        form_past_crops: 'मागील पीक इतिहास',
        form_past_crops_placeholder: 'निवडलेली पिके येथे दिसतात',
        form_past_crops_search_placeholder: 'शोधा आणि पीक जोडा...',
        form_past_crops_description: 'मागील 2-3 हंगामातील पिकांची यादी करा.',
        form_primary_goal_soil: 'मातीसाठी प्राथमिक ध्येय',
        form_primary_goal_soil_placeholder: 'तुमचे मुख्य ध्येय काय आहे?',
        goal_increase_yield: 'उत्पादन वाढवा',
        goal_reduce_fertilizer: 'खताचा खर्च कमी करा',
        goal_long_term_sustainability: 'दीर्घकालीन शाश्वतता',
        goal_improve_water_retention: 'पाणी टिकवून ठेवण्याची क्षमता सुधारा',
        get_soil_advice_button: 'मातीचा सल्ला घ्या',
        loading_analyzing_soil: 'तुमच्या मातीच्या इतिहासाचे विश्लेषण करत आहे...',
        loading_preparing_soil_recommendations: 'आमचे एआय मृदा शास्त्रज्ञ तुमच्या शिफारसी तयार करत आहेत.',
        results_soil_health_analysis: 'प्राथमिक मृदा आरोग्य विश्लेषण',
        results_improvement_recommendations: 'सुधार शिफारसी',
        results_what_to_do: 'काय करावे:',
        results_how_to_implement: 'कसे अंमलात आणावे:',
        results_why_important: 'ते महत्त्वाचे का आहे (फायदे):',
        error_unexpected: 'एक अनपेक्षित त्रुटी आली.',
        irrigation_planner_title: 'तुमच्या सिंचनाचे नियोजन करा',
        irrigation_planner_description: 'एक स्मार्ट, डायनॅमिक सिंचन वेळापत्रक मिळवण्यासाठी तुमच्या शेताचा तपशील प्रविष्ट करा.',
        irrigation_planner_initial_prompt: 'तुमची स्मार्ट सिंचन योजना तयार करा',
        irrigation_planner_initial_prompt_desc: 'एक वैयक्तिकृत, पाणी वाचवणारे वेळापत्रक मिळवण्यासाठी फॉर्म भरा.',
        form_crop_type: 'पिकाचा प्रकार',
        form_crop_type_placeholder: 'उदा. गहू, तांदूळ',
        form_water_source: 'पाण्याचा स्रोत',
        form_water_source_placeholder: 'पाण्याचा स्रोत निवडा',
        water_source_canal: 'कालवा',
        water_source_well: 'विहीर',
        water_source_borewell: 'बोअरवेल',
        water_source_river: 'नदी',
        water_source_rainwater: 'पर्जन्यजल संचयन',
        get_schedule_button: 'वेळापत्रक मिळवा',
        loading_analyzing_farm_data: 'तुमच्या शेताच्या डेटाचे विश्लेषण करत आहे...',
        loading_preparing_plan: 'आमचे एआय तुमची सानुकूल सिंचन योजना तयार करत आहे.',
        results_recommended_schedule: 'शिफारस केलेले वेळापत्रक',
        results_schedule: 'वेळापत्रक',
        results_best_time: 'सिंचनासाठी सर्वोत्तम वेळ',
        results_precautions: 'काळजी',
        results_pesticides: 'कीटकनाशक शिफारसी',
        results_justification: 'समर्थन',
        error_fetching_location_weather: 'स्थान किंवा हवामान डेटा मिळू शकला नाही. कृपया मॅन्युअली प्रविष्ट करा.',
        error_weather_data_not_available: 'हवामान आणि मातीचा डेटा अद्याप उपलब्ध नाही. कृपया थोडा वेळ थांबा आणि पुन्हा प्रयत्न करा.',
        scheme_finder_title: 'सरकारी योजना शोधा',
        scheme_finder_description: 'तुम्ही पात्र असलेल्या सबसिडी आणि योजना शोधा.',
        scheme_finder_initial_prompt: 'संबंधित सरकारी योजना शोधा',
        scheme_finder_initial_prompt_desc: 'लोकप्रिय राष्ट्रीय योजना पाहण्यासाठी तुमचा तपशील प्रविष्ट करा किंवा खाली क्लिक करा.',
        form_primary_crop: 'प्राथमिक पीक',
        form_land_area: 'जमिनीचे क्षेत्र (एकर)',
        find_schemes_button: 'योजना शोधा',
        loading_finding_schemes: 'संबंधित योजना शोधत आहे...',
        loading_searching_programs: 'आमचे एआय तुमच्या गरजेनुसार कार्यक्रम शोधत आहे.',
        results_suggested_schemes: 'तुमच्यासाठी सुचवलेल्या योजना',
        results_popular_schemes: 'लोकप्रिय राष्ट्रीय योजना',
        results_description: 'वर्णन',
        results_eligibility: 'पात्रता',
        results_benefits: 'फायदे',
        results_how_to_apply: 'अर्ज कसा करावा',
        results_no_schemes_title: 'कोणतीही योजना आढळली नाही',
        results_no_schemes_description: 'तुम्ही दिलेल्या माहितीच्या आधारे आम्हाला कोणतीही विशिष्ट सरकारी योजना आढळली नाही. कृपया तुमचे शोध निकष समायोजित करण्याचा प्रयत्न करा.',
        footer_quick_links: 'द्रुत दुवे',
        footer_tools: 'साधने',
        footer_newsletter: 'आमच्या वृत्तपत्राची सदस्यता घ्या',
        footer_newsletter_desc: 'कृषी तंत्रज्ञान आणि सरकारी योजनांवरील नवीनतम अद्यतने मिळवा.',
        footer_subscribe: 'सदस्यता घ्या',
        overall: 'एकूण',
        wheat: 'गहू',
        rice: 'तांदूळ',
        maize: 'मका',
        sugarcane: 'ऊस',
        cotton: 'कापूस',
        soybean: 'सोयाबीन',
        groundnut: 'शेंगदाणा',
        mustard: 'मोहरी',
        potato: 'बटाटा',
        onion: 'कांदा',
        tomato: 'टोमॅटो',
        mango: 'आंबा',
        banana: 'केळी',
        pulses: 'डाळी',
        jute: 'ताग',
        tea: 'चहा',
        coffee: 'कॉफी',
        millet: 'बाजरी',
        barley: 'बार्ली',
        lentil: 'मसूर',
        gram: 'हरभरा',
        sorghum: 'ज्वारी',
        bajra: 'बाजरी',
        turmeric: 'हळद',
        ginger: 'आले',
        chilli: 'मिरची',
        capsicum: 'ढोबळी मिरची',
        brinjal: 'वांगी',
        okra: 'भेंडी',
        cabbage: 'कोबी',
        cauliflower: 'फुलकोबी',
        grapes: 'द्राक्षे',
        apple: 'सफरचंद',
        pomegranate: 'डाळिंब',
        guava: 'पेरू',
        papaya: 'पपई',
    }
};

interface LanguageContextType {
  language: string;
  translations: Translations;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
  loading: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState('English');
  const [translations, setTranslations] = useState<Translations>(TRANSLATIONS_STORE['English']);
  const [loading, setLoading] = useState(false);

  const setLanguage = useCallback((lang: string) => {
    if (lang === language) return;
    
    setLoading(true);
    setLanguageState(lang);
    setTranslations(TRANSLATIONS_STORE[lang] || TRANSLATIONS_STORE['English']);
    
    // Simulate a short delay for the loading overlay to be visible
    setTimeout(() => setLoading(false), 300);
  }, [language]);

  const t = useCallback((key: string): string => {
    return translations[key] || TRANSLATIONS_STORE['English'][key] || key;
  }, [translations]);

  const value = { language, translations, setLanguage, t, loading };

  return (
    <LanguageContext.Provider value={value}>
      <LanguageTransitionOverlay loading={loading} />
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
